# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d81b8ea327a82545e77e61af65e5b9a1103fabf7e99d031d5f14763cb000eb62b961de17fba0bfa7a64084b65fcdf7f835e496c2c0741fd5b3302dda0793d61

test:
  secret_key_base: 2430edfa82d6139a4e5d440c07154da6f6672a17f5fceaef5e11484374466e17d58644f69d1f51009762392e63439598f1e90cab4556b106a43319b5c2150cec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
